Repository open-v2x/dandelion, pull requests merged in 2022-09, with the labels that each got.

#80 fix: wrong MQTT message sent when modifying SystemConfig
  dandelion/mqtt/server.py
  dandelion/mqtt/service/cloud/edge_info_ack.py
Labels: bug

#85 refactor: mqtt topic refactoring (#55)
  dandelion/mqtt/cloud_server.py
  dandelion/mqtt/server.py
  dandelion/mqtt/service/cloud/edge_forward.py
  dandelion/mqtt/service/cloud/edge_info.py
  dandelion/mqtt/service/cloud/edge_info_ack.py
  dandelion/mqtt/service/log/__init__.py
  dandelion/mqtt/service/map/map_down.py
  dandelion/mqtt/service/mng/__init__.py
  dandelion/mqtt/service/query/__init__.py
  dandelion/mqtt/service/rsu/rsu_config.py
  dandelion/mqtt/topic/mng.py
  dandelion/mqtt/topic/rsu_config.py
  dandelion/mqtt/topic/rsu_heartbeat.py
  dandelion/mqtt/topic/rsu_info.py
  dandelion/mqtt/topic/rsu_log.py
  dandelion/mqtt/topic/v2x_config.py
  dandelion/mqtt/topic/v2x_edge.py
  dandelion/mqtt/topic/v2x_rsu.py
Labels: chore

#86 fix: remove extra ， (#63)
  dandelion/mqtt/topic/v2x_edge.py
Labels: bug

#87 fix: modify system_config to send error MQTT
  dandelion/mqtt/__init__.py
  dandelion/mqtt/cloud_server.py
  dandelion/mqtt/server.py
  dandelion/mqtt/service/cloud/edge_forward.py
  dandelion/mqtt/service/cloud/edge_info_ack.py
  dandelion/mqtt/service/map/map_down.py
  dandelion/mqtt/service/query/__init__.py
  dandelion/mqtt/service/rsu/rsu_config.py
  dandelion/periodic_tasks.py
Labels: bug

#90 fix: coexist mode register failure (#72)
  dandelion/api/api_v1/endpoints/system_configs.py
  dandelion/conf/__init__.py
  dandelion/conf/mode.py
  dandelion/main.py
  dandelion/mqtt/cloud_server.py
  dandelion/mqtt/server.py
  etc/dandelion/dandelion.conf.sample
  swagger.json
Labels: bug

#92 fix: remove edges when modifying configuration (#74)
  dandelion/api/api_v1/endpoints/system_configs.py
  dandelion/main.py
  dandelion/mqtt/server.py
  dandelion/mqtt/service/cloud/edge_delete.py
  dandelion/mqtt/topic/v2x_edge.py
  dandelion/periodic_tasks.py
Labels: bug

#95 fix: failed to create RSU
  dandelion/api/api_v1/endpoints/rsus.py
  dandelion/crud/utils.py
Labels: bug

#97 docs: fix sample file name error
  README-zh_CN.rst
  README.rst
Labels: documentation

#98 fix: modify system_config to send error MQTT (#87)
  dandelion/mqtt/__init__.py
  dandelion/mqtt/cloud_server.py
  dandelion/mqtt/server.py
  dandelion/mqtt/service/cloud/edge_forward.py
  dandelion/mqtt/service/cloud/edge_info_ack.py
  dandelion/mqtt/service/map/map_down.py
  dandelion/mqtt/service/query/__init__.py
  dandelion/mqtt/service/rsu/rsu_config.py
  dandelion/periodic_tasks.py
Labels: bug

#91 feat: add apitest check
  .github/workflows/apitest.yml
  .gitignore
  apitest/area.yaml
  apitest/camera.yaml
  apitest/cloud_home.yaml
  apitest/map.yaml
  apitest/map_rsu.yaml
  apitest/mng.yaml
  apitest/radar.yaml
  apitest/rsi.yaml
  apitest/rsi_clc.yaml
  apitest/rsi_cwm.yaml
  apitest/rsi_dnp.yaml
  apitest/rsi_sds.yaml
  apitest/rsm.yaml
  apitest/rsu.yaml
  apitest/rsu_config.yaml
  apitest/rsu_log.yaml
  apitest/rsu_model.yaml
  apitest/rsu_query.yaml
  apitest/rsu_tmp.yaml
  apitest/user_login.yaml
Labels: enhancement

#99 fix: failed to create RSU (#95)
  dandelion/api/api_v1/endpoints/rsus.py
  dandelion/crud/utils.py
Labels: bug

#105 test: add delete_rsu_query case
  apitest/rsu_query.yaml
Labels: test

#102 feat: set the radar status value to false and add it to response
  dandelion/models/radar.py
  dandelion/schemas/radar.py
Labels: enhancement

#106 feat: add apitest check
  .github/workflows/apitest.yml
  apitest/area.yaml
  apitest/camera.yaml
  apitest/cloud_home.yaml
  apitest/map.yaml
  apitest/map_rsu.yaml
  apitest/mng.yaml
  apitest/radar.yaml
  apitest/rsi.yaml
  apitest/rsi_dnp.yaml
  apitest/rsm.yaml
  apitest/rsu.yaml
  apitest/rsu_config.yaml
  apitest/rsu_log.yaml
  apitest/rsu_model.yaml
  apitest/rsu_query.yaml
  apitest/rsu_tmp.yaml
  apitest/user_login.yaml
Labels: enhancement

#107 feat: add spat api
  apitest/spat.yaml
  dandelion/alembic/versions/0cc3f6cfa16b_add_spat.py
  dandelion/api/api_v1/api.py
  dandelion/api/api_v1/endpoints/spats.py
  dandelion/crud/__init__.py
  dandelion/crud/crud_spat.py
  dandelion/models/__init__.py
  dandelion/models/rsu.py
  dandelion/models/spat.py
  dandelion/mqtt/server.py
  dandelion/mqtt/service/rsu/rsu_spat.py
  dandelion/mqtt/topic/v2x_rsu.py
  dandelion/schemas/__init__.py
  dandelion/schemas/spat.py
  swagger.json
Labels: enhancement

#108 refactor: uniform case of fields
  apitest/spat.yaml
  dandelion/schemas/lidar.py
  dandelion/schemas/radar.py
  dandelion/schemas/spat.py
  swagger.json
Labels: chore

#109 feat: add multi-node test cases
  apitest/multi_node.yaml
Labels: enhancement

#116 fix: change the length of camera stream_url
  dandelion/alembic/versions/ca29ab3a1fc7_change_camera_stream_url_length.py
  dandelion/models/camera.py
Labels: bug

#119 feat: add lidar oneline rate to response
  dandelion/api/api_v1/endpoints/cloud_homes.py
  dandelion/schemas/cloud_home.py
  swagger.json
Labels: enhancement

#121 feat: add error capture and return
  dandelion/api/api_v1/endpoints/lidars.py
  dandelion/api/api_v1/endpoints/radars.py
  dandelion/api/api_v1/endpoints/spats.py
Labels: enhancement
