Repository open-v2x/dandelion, pull requests merged in 2022-08, with the labels that each got.

#13 ci: add deploy to aio step in ci workflow
  .github/workflows/ci.yml
Labels: chore

#15 ci: add deploy to aio step in ci workflow
  .github/workflows/ci.yml
Labels: chore

#20 fix: add "rsuModelName" to RSU detailed results
  dandelion/models/rsu.py
  dandelion/schemas/rsu.py
  swagger.json
Labels: bug

#21 fix: add "rsuId"&&"areaCode" to query "cameras"&&"radars" list
  dandelion/api/api_v1/endpoints/cameras.py
  dandelion/api/api_v1/endpoints/radars.py
  dandelion/crud/crud_camera.py
  dandelion/crud/crud_radar.py
  swagger.json
Labels: bug

#23 fix: add delete api to RSU Query && Query list in reverse order
  dandelion/api/api_v1/endpoints/rsu_queries.py
  dandelion/crud/crud_rsu_query.py
  dandelion/crud/crud_rsu_query_result.py
  dandelion/mqtt/service/query/rsu_query_up.py
  swagger.json
Labels: bug

#24 feat: add polling collect device information to RSU
  dandelion/api/api_v1/endpoints/rsus.py
  dandelion/main.py
  dandelion/periodic_tasks.py
  dandelion/schemas/__init__.py
  dandelion/schemas/rsu.py
  requirements.txt
  swagger.json
Labels: enhancement

#28 feat: add MQTT Notice to update system_config
  dandelion/api/api_v1/endpoints/system_configs.py
  dandelion/mqtt/service/algorithm/system_config.py
Labels: enhancement

#31 fix: modify RSI duration event_radius event_priority is empty by default
  dandelion/models/rsi_event.py
  dandelion/schemas/rsi_event.py
  swagger.json
Labels: bug

#34 fix: add sort to Event list
  dandelion/api/api_v1/endpoints/rsi_clcs.py
  dandelion/api/api_v1/endpoints/rsi_cwms.py
  dandelion/api/api_v1/endpoints/rsi_dnps.py
  dandelion/api/api_v1/endpoints/rsi_events.py
  dandelion/api/api_v1/endpoints/rsi_sdss.py
  dandelion/api/api_v1/endpoints/rsm_participants.py
  dandelion/crud/crud_rsi_clc.py
  dandelion/crud/crud_rsi_cwm.py
  dandelion/crud/crud_rsi_dnp.py
  dandelion/crud/crud_rsi_event.py
  dandelion/crud/crud_rsi_sds.py
  dandelion/crud/crud_rsm_participant.py
  dandelion/schemas/rsi_clc.py
  dandelion/schemas/rsi_cwm.py
  dandelion/schemas/rsi_dnp.py
  dandelion/schemas/rsi_sds.py
  dandelion/schemas/utils.py
  swagger.json
Labels: bug

#37 fix: add "rsuModelName" to RSU detailed results (#20)
  dandelion/models/rsu.py
  dandelion/schemas/rsu.py
  swagger.json
Labels: bug

#38 fix: add "rsuId"&"areaCode" to query "cameras"&"radars" list (#21)
  dandelion/api/api_v1/endpoints/cameras.py
  dandelion/api/api_v1/endpoints/radars.py
  dandelion/crud/crud_camera.py
  dandelion/crud/crud_radar.py
  swagger.json
Labels: bug

#39 fix: add delete api to RSU Query && Query list in reverse order (#23)
  dandelion/api/api_v1/endpoints/rsu_queries.py
  dandelion/crud/crud_rsu_query.py
  dandelion/crud/crud_rsu_query_result.py
  dandelion/mqtt/service/query/rsu_query_up.py
  swagger.json
Labels: bug

#40 feat: add polling collect device information to RSU (#24)
  dandelion/api/api_v1/endpoints/rsus.py
  dandelion/main.py
  dandelion/periodic_tasks.py
  dandelion/schemas/__init__.py
  dandelion/schemas/rsu.py
  requirements.txt
  swagger.json
Labels: enhancement

#41 feat: add MQTT Notice to update system_config (#28)
  dandelion/api/api_v1/endpoints/system_configs.py
  dandelion/mqtt/service/algorithm/system_config.py
Labels: enhancement

#42 fix: query camera and radar offline number (#29)
  dandelion/api/api_v1/endpoints/cloud_homes.py
Labels: bug

#43 fix: modify RSI duration event_radius event_priority is empty by defa…
  dandelion/models/rsi_event.py
  dandelion/schemas/rsi_event.py
  swagger.json
Labels: bug

#45 fix: add sort to Event list (#34)
  dandelion/api/api_v1/endpoints/rsi_dnps.py
  dandelion/api/api_v1/endpoints/rsi_events.py
  dandelion/api/api_v1/endpoints/rsm_participants.py
  dandelion/crud/crud_rsi_dnp.py
  dandelion/crud/crud_rsi_event.py
  dandelion/crud/crud_rsm_participant.py
  dandelion/schemas/utils.py
  swagger.json
Labels: bug

#48 doc: add doc introduction
  doc/catalog-tree.md
  doc/dandelion.md
  doc/how-to-develop.md
  doc/technology-stack.md
Labels: documentation

#50 mysql password supports special characters
  dandelion/alembic/env.py
  dandelion/db/session.py
Labels: bug

#51 fix: Modify system config notification timing
  dandelion/api/api_v1/endpoints/system_configs.py
  dandelion/mqtt/service/algorithm/system_config.py
  dandelion/mqtt/service/cloud/edge_info_ack.py
Labels: bug

#53 fix: modify notification timing to system config (#51)
  dandelion/api/api_v1/endpoints/system_configs.py
  dandelion/mqtt/service/algorithm/system_config.py
  dandelion/mqtt/service/cloud/edge_info_ack.py
Labels: bug

#55 refactor: mqtt topic refactoring
  dandelion/mqtt/cloud_server.py
  dandelion/mqtt/server.py
  dandelion/mqtt/service/cloud/edge_forward.py
  dandelion/mqtt/service/cloud/edge_info.py
  dandelion/mqtt/service/cloud/edge_info_ack.py
  dandelion/mqtt/service/log/__init__.py
  dandelion/mqtt/service/map/map_down.py
  dandelion/mqtt/service/mng/__init__.py
  dandelion/mqtt/service/query/__init__.py
  dandelion/mqtt/service/rsu/rsu_config.py
  dandelion/mqtt/topic/mng.py
  dandelion/mqtt/topic/rsu_config.py
  dandelion/mqtt/topic/rsu_heartbeat.py
  dandelion/mqtt/topic/rsu_info.py
  dandelion/mqtt/topic/rsu_log.py
  dandelion/mqtt/topic/v2x_config.py
  dandelion/mqtt/topic/v2x_edge.py
  dandelion/mqtt/topic/v2x_rsu.py
Labels: chore

#62 fix: mysql password supports special characters (#50)
  dandelion/alembic/env.py
  dandelion/db/session.py
Labels: bug

#61 fix: redis and mysql support [\/:
  dandelion/db/redis_pool.py
  dandelion/db/session.py
Labels: bug

#65 fix: modify edge site name,the old and new data exist at the same time
  dandelion/api/api_v1/endpoints/system_configs.py
Labels: bug

#64 fix: redis and mysql support [\/: (#61)
  dandelion/db/redis_pool.py
  dandelion/db/session.py
Labels: bug

#66 fix: special handling of sqlite connections
  dandelion/alembic/env.py
Labels: bug

#67 fix: special handling of sqlite connections
  dandelion/alembic/env.py
Labels: bug

#70 ci: change install script download method in ci.yml
  .github/workflows/ci.yml
Labels: chore

#71 ci: change install script download method in ci.yml
  .github/workflows/ci.yml
Labels: chore
